### ISSUE TITLE
Form Errors are in Portuguese

### ISSUE THREAD

**Issue by peterflat** [zekitow/codeigniter-scaffold#4]
I spent about 10 minutes trying to find where the localization settings are...  Correct me if I am wrong but are the form errors in Portuguese by default?

**Comment by zekitow** [comment]
Hi, 

By default, I've changed just the file:

/system/language/english/form_validation_lang.php for portuguese.

There you can configure any erro message if you want too.

Thanks for contact! Support the opensource! Fork-it or make a pull request.

Thank you!

Cheers.

**Comment by peterflat** [comment]
Awesome.  Thanks for the note!

**Comment by zekitow** [comment]
Thanks, any problem, 

Please, contact me!

Cheers
